services:
  livekit:
    image: livekit/livekit-server:latest
    command: --dev --bind 0.0.0.0
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50100:50000-50100/udp"
    environment:
      LIVEKIT_KEYS: "mykey: mysecret"

  coturn:
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    command: >
      -n
      --log-file=stdout
      --lt-cred-mech
      --fingerprint
      --realm=liveclass.app
      --user=testuser:testpass
